// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmVZ2chR8p9xbsNYH0lgWWgEbtP_XLTrE',
    appId: '1:482955327932:web:4314ea42dbea9e83e4d3b9',
    messagingSenderId: '482955327932',
    projectId: 'finova-e471b',
    authDomain: 'finova-e471b.firebaseapp.com',
    storageBucket: 'finova-e471b.firebasestorage.app',
    measurementId: 'G-EHDFHWQTFT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ5jgfGYateoFhm0w3dSHXwJ4MJSEOrI4',
    appId: '1:482955327932:android:a236556a40a5e03ee4d3b9',
    messagingSenderId: '482955327932',
    projectId: 'finova-e471b',
    storageBucket: 'finova-e471b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxwaZY8fMUsOiSAGi8y_-qWvKeBQ7LnDc',
    appId: '1:482955327932:ios:58c98aadce45c465e4d3b9',
    messagingSenderId: '482955327932',
    projectId: 'finova-e471b',
    storageBucket: 'finova-e471b.firebasestorage.app',
    iosBundleId: 'com.example.finova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxwaZY8fMUsOiSAGi8y_-qWvKeBQ7LnDc',
    appId: '1:482955327932:ios:58c98aadce45c465e4d3b9',
    messagingSenderId: '482955327932',
    projectId: 'finova-e471b',
    storageBucket: 'finova-e471b.firebasestorage.app',
    iosBundleId: 'com.example.finova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmVZ2chR8p9xbsNYH0lgWWgEbtP_XLTrE',
    appId: '1:482955327932:web:63c856831b7816c7e4d3b9',
    messagingSenderId: '482955327932',
    projectId: 'finova-e471b',
    authDomain: 'finova-e471b.firebaseapp.com',
    storageBucket: 'finova-e471b.firebasestorage.app',
    measurementId: 'G-G91P15PNW6',
  );
}
